ALTER TABLE [dbo].[BasketPaymentPayPal]
    ADD CONSTRAINT [PK_BasketPaymentPayPal] PRIMARY KEY CLUSTERED ([BasketID] ASC, [PaymentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

