ALTER TABLE [dbo].[BaseProduct]
    ADD CONSTRAINT [PK_BaseProduct] PRIMARY KEY CLUSTERED ([BaseProductId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

