ALTER TABLE [dbo].[BasketPayment]
    ADD CONSTRAINT [PK_BasketPayment] PRIMARY KEY CLUSTERED ([BasketID] ASC, [PaymentID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

