ALTER TABLE [dbo].[BasketShipping]
    ADD CONSTRAINT [PK_BasketShipping_1] PRIMARY KEY CLUSTERED ([BasketID] ASC, [ShippingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

