ALTER TABLE [dbo].[BasketShippingMethod]
    ADD CONSTRAINT [PK_BasketShippingMethod_1] PRIMARY KEY CLUSTERED ([BasketId] ASC, [ShippingId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

