ALTER TABLE [dbo].[ControlId]
    ADD CONSTRAINT [PK_ControlId] PRIMARY KEY CLUSTERED ([ControlId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

