ALTER TABLE [dbo].[Colonia]
    ADD CONSTRAINT [PK_Colonia] PRIMARY KEY CLUSTERED ([IdPais] ASC, [IdEstado] ASC, [IdMunicipio] ASC, [IdColonia] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

