ALTER TABLE [dbo].[BasketDetail]
    ADD CONSTRAINT [PK_CarritoComprasDetalle] PRIMARY KEY CLUSTERED ([BasketId] ASC, [LineId] ASC, [BasketDetailId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

