ALTER TABLE [dbo].[Estado]
    ADD CONSTRAINT [PK_Estado] PRIMARY KEY CLUSTERED ([IdPais] ASC, [IdEstado] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

