ALTER TABLE [dbo].[InventoryProductCategory]
    ADD CONSTRAINT [PK_InventarioProducto_1] PRIMARY KEY CLUSTERED ([InventoryID] ASC, [CategoryID] ASC, [ProductID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

