ALTER TABLE [dbo].[InventoryProduct]
    ADD CONSTRAINT [PK_InventoryProduct] PRIMARY KEY CLUSTERED ([InventoryID] ASC, [ProductID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

