ALTER TABLE [dbo].[InventoryCategory]
    ADD CONSTRAINT [PK_InventarioCategoria] PRIMARY KEY CLUSTERED ([InventoryID] ASC, [CategoryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

