ALTER TABLE [dbo].[Inventory]
    ADD CONSTRAINT [PK_Inventario] PRIMARY KEY CLUSTERED ([InventoryID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

