ALTER TABLE [dbo].[Municipio]
    ADD CONSTRAINT [PK_Municipio] PRIMARY KEY CLUSTERED ([IdPais] ASC, [IdEstado] ASC, [IdMunicipio] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

