ALTER TABLE [dbo].[OrderShipping]
    ADD CONSTRAINT [PK_OrderShipping] PRIMARY KEY CLUSTERED ([OrderID] ASC, [OrderShippingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

