ALTER TABLE [dbo].[PropertySubCategory]
    ADD CONSTRAINT [PK_PropertySubCategory] PRIMARY KEY CLUSTERED ([PropertyCategoryId] ASC, [PropertySubCategoryId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

