ALTER TABLE [dbo].[ShippingCost]
    ADD CONSTRAINT [PK_ShippingCost_1] PRIMARY KEY CLUSTERED ([ShippingCostId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

