ALTER TABLE [dbo].[ShippingCompany]
    ADD CONSTRAINT [PK_ShippingCompany] PRIMARY KEY CLUSTERED ([ShippingCompanyId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

