ALTER TABLE [dbo].[UsuarioDireccion]
    ADD CONSTRAINT [PK_UsuarioDireccion] PRIMARY KEY CLUSTERED ([UserId] ASC, [AddressId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

